# Sidebar navigation

- label: '简介'
  link: '/'
- label: 现存网页
  items:
    - label: 'Mirror'
      link: '/pages/mirror'
    - label: 'Repo'
      link: '/pages/repo'
    - label: 'Grafana'
      link: '/pages/grafana'
    - label: 'Nextcloud'
      link: '/pages/nextcloud'
    - label: 'Sharelatex'
      link: '/pages/sharelatex'